### ISSUE TITLE
Main plugin branch under mac - no files are saved to disk

### ISSUE THREAD

**Issue by shayo** [open-ephys/plugin-GUI#135]
Hi,
I have a weird issue on my mac. When I click record, only the xml file is generated. Nothing else is saved to disk. This is happening on the master plug in branch.
It is reproducible. Seems like the first time I ran the exe, it worked, but then subsequent calls suffer from this problem.

**Comment by shayo** [comment]
It's even worse. When I click record, the stream stops and nothing is updated on the screen...

**Comment by aacuevas** [comment]
Hi,

Does it happen with both KWIK and open ephys formats or just the latter? How many channels are you trying to save?
Also, could you please check if this also happens on the testing and/or development branches? I do remember some patches regarding recording since last master update, but I'm not sure if they might be relevant to your issue.

Aarón.

**Comment by jsiegle** [comment]
I've been testing extensively on Mac, and this doesn't seem to be a problem anymore.
