### ISSUE TITLE
File Reader Freezes Open-Ephys Linux Build

### ISSUE THREAD

**Issue by whitepine** [open-ephys/plugin-GUI#161]
When trying to select a file to read from the "File Reader" plug-in, open-ephys crashes. I think this is because it by default uses a Window's convention for specifying the drive: "F:". Is there any easy fix for this?

**Comment by aacuevas** [comment]
Does it crash when you click on the open file button? (The "F:" is not a Windows drive, but short for "File")
If so it might be due to the bug stated in #42 for which JUCEs dialog sometimes appear hidden, which makes the GUI appear to be frozen.
We added the compiler flag stated on that issue page to the build process but it seems that at some point got deleted without us noticing. Building the GUI again with that flag should solve your issue.

**Comment by whitepine** [comment]
Your suggestion fixed the problem!
