### ISSUE TITLE
Network Events causes crashes when restarting connection

### ISSUE THREAD

**Issue by kmichaelfox** [open-ephys/plugin-GUI#174]
Clicking the [restarting connection] button in the Network Events plugin can sometimes cause crashes for the GUI application on the Testing branch. There are 3 behavior's that I've observed so far:

Very rarely, clicking Restart Connection soon after adding the plugin can cause an application crash.
Much more often, clicking Restart Connection more than once (either in rapid succession or with a several second delay) can cause the application to hang.
Sometimes, if the Restart Connection button is clicked and the application survives without crashing, deleting the Network Events plugin can cause a crash.

This sounds like an exception or error from attempting to bind/connect to an unavailable socket.

**Comment by aacuevas** [comment]
I only getting a crash sometimes on Linux, can't replicate on windows. The issue seems to originate within zmq_recv. From what I've read, it should exit gracefully with an error code whenever the context is destroyed in another thread (which is what we do in NetworkEvents::closesocket() ) but it seems sometimes it crashes instead.

May be a bug in the zmq lib itself, but we need to investigate further.
