### ISSUE TITLE
Put back beta lfp viewer

### ISSUE THREAD

**Issue by jonnew** [open-ephys/plugin-GUI#226]
Current lfp viewer is broken for multi processor sources.

**Comment by jsiegle** [comment]
I'm fine with adding it back to the dev branch for now, but we will also need to figure out what's wrong with the new viewer. What configuration breaks it?

**Comment by jonnew** [comment]
I don't agree. I think that breaking changes should probably not take precedence over stable but limited code. 

The major issue is that I cannot change the sub-processor that I'm looking at. Changing it in the drop down menu has no affect on the channels that are shown.

**Comment by jsiegle** [comment]
That functionality is working in the dev branch... @aacuevas, do you think we could be ready for another master release in the next week or so?

In the meantime, I added the beta LFP Viewer back to the dev branch, because it has the ability to display multiple subprocessors simultaneously, which the newer LFP Viewer does not have.
