### ISSUE TITLE
combining continuous files

### ISSUE THREAD

**Issue by wehr-do** [open-ephys/plugin-GUI#248]
Hi,
I'm trying to combine two or more continuous files to be able to cluster all of my recordings from the same session by KiloSort at once. 

Currently, this is what I do:
% load data from file 1
NUM_HEADER_BYTES = 1024;
fid1 = fopen(filename1, 'r');
hdr1 = fread(fid1, NUM_HEADER_BYTES, 'char*1');
samples1 = fread(fid1, 'int16');
% load data from file 2
fid2 = fopen(filename2, 'r');
hdr2 = fread(fid2, NUM_HEADER_BYTES, 'char*1');
samples2 = fread(fid2, 'int16');
% write data into new file
fid_final=fopen(sprintf('100_CH%d.continuous',i), 'w');
fwrite(fid_final, hdr1, 'char*1'); %I just put the first header in there, since Kilosort expects it.
fwrite(fid_final, samples1, 'int16');
fwrite(fid_final, samples2, 'int16');
fclose(fid1);
fclose(fid2);
fclose(fid_final);
    
When I load new file with load_open_ephys_data, it looks like the script did what it should do. But when I  cluster the data with Kilosort, it looks like my spikes are not on the correct channels. Kilosort does not read combined files correctly, but it does read original files correctly. 
Any suggestions about what you thing might be causing an issue?

Thank you.

**Comment by angelonc** [comment]
I think the issue may have to do with how the raw openEphys.continuous files are recorded. There is a short buffer of 1024 samples that is padded by 5 samples on either side (the 10 samples do not correspond to actual data, but mark the transition between records... I think). If you are combining two files, you might be incidentally concatenating two record markers next to each other (the end record marker of the last record in your first recording, and the start record marker of the last record in your second recording).

Because KiloSort then loads the openEphys files and then interleaves them into flatbinary format, having a few extra samples midway through will vastly change how the channels are mapped. So... I think that's what the issue might be, but you'd have to look carefully at the data to verify this!

That said, a couple things to think about:

- You'll make your life a whole lot easier by keeping time periods you'd like to cluster together in the same recording. I will only stop a recording when I change recording settings or move my probe. By concatenating recordings, you will have discontinuities at the minimum, and if you changed the settings between recordings, it is hard to interpret your clustering results.

- I'd also recommend recording in binary format instead of openEphys. This way, the data is already in a format that KiloSort natively loads and will save you time and storage space in the clustering step (when KiloSort gets openEphys files, it loads them and writes them out to a flat binary file anyway, then loads the new file and does the processing).
