### ISSUE TITLE
Why "enable optimization for linux debug"?

### ISSUE THREAD

**Issue by ethanbb** [open-ephys/plugin-GUI#310]
This applies to the development branch.

In the CMakeLists files for the GUI, plugins, and common libs, optimization is enabled on Linux even for debug builds by manually adding the compiler flag `-O3`.

Why? CMake comes with the handy configuration type `RelWithDebInfo`, so you can use that if you want to debug with optimizations. On the other hand, sometimes it's helpful to debug _without_ optimizations.

**Comment by aacuevas** [comment]
This comes far back. A long time ago we enabled optimizations on Linux Debug because, without it, the GUI ran too slowly to be even testable.
So when I moved everything to CMake, I just kept it the same. But it is true that the GUI design has improved much since then, so it is quite possible that it is not necessary anymore. We'll have to test to be sure.
