### ISSUE TITLE
[Feature Request] Support network events recording to binary format.

### ISSUE THREAD

**Issue by hotsoupisgood** [open-ephys/plugin-GUI#316]
Based on the wiki, Network Events only records to open ephys and kwik. If this is not still the case, how does one change the format?

**Comment by aacuevas** [comment]
I have removed those lines, since all the formats have been able to record events for a while. In fact, Binary is being to become the recommended way of storing data soon.

In any case, the recording format can be selected by expanding the control panel clicking at the triangle icon and then selecting the format in the dropdown.
