### ISSUE TITLE
NpxExtractor

### ISSUE THREAD

**Issue by macayladonegan** [open-ephys/plugin-GUI#366]
Hi all,

I downloaded the executables for the gui, but it seems to be missing the tools folder? Is there another way to get a hold of NpxExtractor.exe?

Best,
Macayla

**Comment by jsiegle** [comment]
It's no longer included in the binary release, but you can download it here: https://github.com/open-ephys-GUI-binaries/open-ephys/tree/neuropix/Tools/NpxExtractor

**Comment by macayladonegan** [comment]
Does this work with the .npx2 data format? I tried running this but nothing showed up in my output directory

**Comment by jsiegle** [comment]
It should work with .npx2 files. It can be slow to start, as it searches through the entire file to count the number of probes in the recording. But if it seemed like it completed without writing anything, then there's something wrong.

I added the NpxExtractor executable to the `ecephys_spike_sorting` repo, since we're no longer updating `open-ephys-gui-binaries`: https://github.com/AllenInstitute/ecephys_spike_sorting/tree/master/ecephys_spike_sorting/modules/extract_from_npx/NpxExtractor/Release

Let me know if that one also doesn't work, and we can continue to troubleshoot.

**Comment by jsiegle** [comment]
Hi there! Did you ever get a chance to test this out?

**Comment by macayladonegan** [comment]
Yes it ended up working thanks!
