### ISSUE TITLE
Cannot find the plugin generator

### ISSUE THREAD

**Issue by teristam** [open-ephys/plugin-GUI#373]
Hi,

I must have missed something. I want to follow the wiki to use the plugin generator, but I can't find it anywhere in the program or the installation folder. How do I open the plugin generator? Or is it a separate download ? Thanks!

**Comment by anjaldoshi** [comment]
Hi,

Plugin Generator is no longer used for making your own plugins from scratch as plugin-GUI now uses (since v0.4.5) CMake instead of Projucer for generating build files. The documentation site is outdated and we working on a new documentation site (https://open-ephys.github.io/gui-docs/) that already has updated installation and user guides, but we still need to finish the developer guide. For creating plugins from scratch, you need to refer to the [plugin template](https://github.com/open-ephys-plugins/OEPlugin) repository and follow the simple instructions to create new plugins.

Let us know if you need any further help.
