### ISSUE TITLE
Open Ephys GUI show version mismatch

### ISSUE THREAD

**Issue by asd121212666** [open-ephys/plugin-GUI#388]
We updated the Open Ephys GUI to v0.5.5.5. we opened the GUI but it stops opening the interface entirely today. 
The Debug Console opens, but the GUI window stays completely white. The information we got is the following:
![image](https://user-images.githubusercontent.com/73580211/98515455-15c3c880-22a6-11eb-9c7f-a159d166f4bd.png)
 we check "Yes" and then the error information  we got is the following:
![image](https://user-images.githubusercontent.com/73580211/98515628-473c9400-22a6-11eb-8d90-384ec0a18444.png)

**Comment by anjaldoshi** [comment]
Hi,

Did you select `Yes` in both the alert widows? Does it still stay completely white when you do so? 

Basically, the version mismatch alert window showed up because the config file that was saved in the last run was from older version and then when you updated to the latest version, the GUI showed a warning that it may not load the config from previous version properly. This is a standard warning, because in some cases, updates to the GUI causes config file to not load properly, which may be the case over here if the GUI doesn't respond even after selecting `Yes` in both the alerts. 

To fix this, can you remove both `lastConfig.xml` and `recoveryConfig.xml` files from `C:\ProgramData\Open Ephys` and then run the GUI again? If the ProgramData directory is not visible, you can unhide it by following [these steps](https://support.microsoft.com/en-us/windows/view-hidden-files-and-folders-in-windows-10-97fbc472-c603-9d90-91d0-1166d1d9f4b5).  Also, before deleting those files, can you share those files over here so that we can figure out if anything is wrong with the config files?

Thanks,
Anjal
