### ISSUE TITLE
Error in VS for debug Gui RHA2000

### ISSUE THREAD

**Issue by carolinav24** [open-ephys/plugin-GUI#39]
Hi, I´m trying to install the open-ephys in Windows 7, but when I debug the open-ephys.sln It mark 2 errors that it didnt found:
Source/Processors/DataThreads/IntanThread.cpp
Source/Processors/SourceNode/SourceNode.cpp

But I have this two sources...So, I dont know whats is going on with that.

I appreciate the help!

**Comment by aacuevas** [comment]
Do you mean the RHA branch from the old monolithic repo? Which VS are you using?

**Comment by carolinav24** [comment]
I download it from the RHA2200 eval branch (https://github.com/open-ephys/GUI.git).
I´m using VS 2013 ultimate version.

**Comment by malfatti** [comment]
Indeed, those errors are from compiling rha2000-eval branch of non-plugin GUI.

Is there a RHA source plugin for plugin-GUI?

**Comment by aacuevas** [comment]
There isn't yet. The build is effectively broken, at least for Windows. The best efficient route from here, I believe, is making it into a plugin for all architectures, I can probably have that done in a couple of days.
I'll keep you posted.

**Comment by malfatti** [comment]
Thanks a lot @aacuevas! 

About the VS file being messed up, this is probably my fault :( I submitted some time ago a pull request (https://github.com/open-ephys/GUI/commit/ec85c770cea3b9a27f9086ba1c3ace438faf1102) in the rha2000-eval branch of the GUI that merged several improvements made in master. I tested and it compiles perfectly (with both RHA and FPGA working) in linux, but I didn't test other OSes. Sorry about that :( Probably replacing VS files in the current rha2000-eval by the ones in rha2000-eval at @jvoigts 's commit (https://github.com/open-ephys/GUI/commit/f3359ffbb1592f01801b8404ca08a5ea23aac919) would solve it.

Sorry again for the mess, I only started a pull request because it worked so nice in linux :)

**Comment by carolinav24** [comment]
Thanks to both of you!!!

**Comment by carolinav24** [comment]
Hi! any news?

**Comment by jsiegle** [comment]
Closing this issue because the 16-channel RHA2000 Eval Board is not supported in the plugin-based version of the GUI.
