### ISSUE TITLE
Plugin Help - request buffer size

### ISSUE THREAD

**Issue by ANickerson** [open-ephys/plugin-GUI#466]
Hello,

I am writing a filter plugin which requires buffering a set number of samples before processing (ca. 5ms).
Currently I am creating an extra buffer and copying the data into there until ready to process.
This is working ok, but it creates a delay in the channel relative to the unfiltered paths.

Is there a way to request a specific number of samples for the read buffer?

Thanks!

**Comment by aacuevas** [comment]
Unfortunately, there is no way for a plugin to request a specific buffer. The acquisition board generates data at a specific rate, which gets sent to the computer in usb buffers. Then the GUI executes a regular timed callback, processing any amount of full buffers in its memory (a usb buffer in transit would be processed in the next callback). Since those process are asynchronous, the amount of data in each buffer might vary, so the plugins need to check the actual number of samples each buffer.

Users can set the timing of the processing callback within the GUI, by clicking on the "Latency" label and modifying settings, but that is not controlable by plugins.
