### ISSUE TITLE
API for Accessing PCA Space/Spike Waveforms

### ISSUE THREAD

**Issue by d-bi** [open-ephys/plugin-GUI#500]
Hi,

I wonder whether there is a way to access spike information programmatically (in another plugin), specifically PCA coordinates and/or the raw waveforms that pass the threshold?

Thanks in advance.

**Comment by jsiegle** [comment]
The raw waveforms are available in the `Spike` objects that are passed to each plugin's `handleSpike()` method (after deserializing them from the incoming `MidiMessage`).

To access the waveform sample values for one channel, you can use the following code:

```c++
int channelIndex = 0;
const float* waveform = spike->getDataPointer(channelIndex);
```

The PCA coordinates are not sent between processors.  But you should take a look at the soon-to-be-released version of the Spike Sorter plugin, which has been substantially cleaned up compared to the one currently in the `master` branch: https://github.com/open-ephys-plugins/spike-sorter

This version works on pre-detected spikes, rather than implementing its own detector, and computes the PC coordinates for each incoming spike. Perhaps you could use that as a starting point?
