### ISSUE TITLE
sync_messages.txt missing data and start values are inconsistent with timestamps.npy

### ISSUE THREAD

**Issue by geffenlab** [open-ephys/plugin-GUI#502]
In some of our recent neuropixels recordings we noticed some troublesome bugs with the sync_messages.txt file.

A recent recording was missing most of the processors in this file, only containing the one for the NIDAQ card we use for events:
`Processor: NI-DAQmx Id: 102 subProcessor: 0 start time: 55208001@30000Hz`

Per issue #486 and #458 we checked the start times of each processors timestamps.npy file to use for event synchronization. To verify this method, we checked another recording with an intact sync_messages file:
`Software time: 400507@10000000Hz
Processor: Neuropix-PXI Id: 100 subProcessor: 0 start time: 400225@30000Hz
Processor: Neuropix-PXI Id: 100 subProcessor: 1 start time: 33353@2500Hz
Processor: NI-DAQmx Id: 102 subProcessor: 0 start time: 251001@30000Hz`

However, loading and comparing the first timestamps in the Neuropix-PXI and NIDAQmx timestamps.npy files showed that while the Neuropixels timestamp matched, the NIDAQ timestamp was off from the one in the sync_messages file by exactly 2000 samples (249001 in timestamps.npy). We checked another recording and found the same issue, except the first timestamp for the NIDAQ came 1000 samples early relative to the sync_message file.

Any help would be much appreciated... we have previously used these sync_message times to align our events to the neural data, but these seemingly random mismatches in the start time call this alignment into question (ie. they would be off by 33.3 or 66.6ms in the examples here)

**Comment by medengineer** [comment]
Hi, 

In the case of discrepancy between sync_messages.txt and the timestamps.npy file, the timestamps.npy file should take precedence. The sync messages are generated by the source processors and it can take 1 to 2 buffers before the first data is written to disc via a Record Node. The NIDAQ buffer size is exactly 1000 samples. This is fixed in the next major release (0.6.0), where sync message logic has been moved into the Record Node.
