### ISSUE TITLE
Upgrade from v0.5.5.4->0.6.3, timestamps in events files now in sample #, instead of time in sec.

### ISSUE THREAD

**Issue by jays314159** [open-ephys/plugin-GUI#553]
When I load an events file in Matlab using 'load_open_ephys_data' to read TTL events and their times, the timestamps I got before used to be in seconds, matching that of times in '.continuous' files. After the upgrade, they seem to be measured as sample numbers. I'm using Intan.

Is this an intentional change, or is there some new setting that I missed?

**Comment by medengineer** [comment]
The change is intentional, as of v0.6.0 we wanted to remove the ambiguity between sample_numbers and timestamps across formats. 

I recommend checking out the [open-ephys-matlab-tools repository](https://github.com/open-ephys/open-ephys-matlab-tools) that provides a more user-friendly object-oriented interface that is up-to-date with the latest changes. The examples folder shows how timestamps / sample_numbers are used and consistent across all formats.

**Comment by jays314159** [comment]
Ah, OK. 

I upgraded to use the native HTTP server functionality, but because we already have pipeline setup for the old version (and don't feel like changing it yet again), I'll have to go back to previous version and use Network Events plugin. 

Thank you for quick confirmation, in any case.
