### ISSUE TITLE
can not see any plugins on the plugin installer 

### ISSUE THREAD

**Issue by JieZ1230** [open-ephys/plugin-GUI#617]
When I open the plugin installer, I don't see the plugin list. I can't select the plugin I need on the left.

Computers are network connected. How can this problem be solved

![1](https://github.com/open-ephys/plugin-GUI/assets/149473737/0f47a473-fcd1-4a55-ac9d-5b30ead0b91f)

**Comment by anjaldoshi** [comment]
Hi - I just verified that both of the services necessary for the Plugin Installer to work are up and running. It could be because your Network Admin has blocked access to certain endpoints/URLs automatically and that's why the Plugin Installer is not able to access its cloud gateway to fetch the data. Can you try to access the following URL directly via your browser using the same machine and see if it loads without any errors for you?
https://open-ephys-plugin-gateway.herokuapp.com

**Comment by JieZ1230** [comment]
> Hi - I just verified that both of the services necessary for the Plugin Installer to work are up and running. It could be because your Network Admin has blocked access to certain endpoints/URLs automatically and that's why the Plugin Installer is not able to access its cloud gateway to fetch the data. Can you try to access the following URL directly via your browser using the same machine and see if it loads without any errors for you? https://open-ephys-plugin-gateway.herokuapp.com

HI! Thank you for your help. I visited the website you provided, but it could not be opened successfully, and it said "Cannot access this page". How can I solve this problem?

Thank you again！
BEST!

**Comment by anjaldoshi** [comment]
That means the site is blocked on your network, and you'll have to whitelist it. If your network is managed by your institution/organization then you'll have to ask your IT team to whitelist the site for you.

**Comment by JieZ1230** [comment]
> That means the site is blocked on your network, and you'll have to whitelist it. If your network is managed by your institution/organization then you'll have to ask your IT team to whitelist the site for you.

Thanks very much for your help. The problem has been solved!!
