### ISSUE TITLE
Buffer size interface button not visible in release v0.4.1

### ISSUE THREAD

**Issue by jsiegle** [open-ephys/plugin-GUI#79]
In the current binaries (on Mac at least), the buffer size button in the control panel is invisible (but still can be clicked). It should be an easy fix, but I wanted to make a record of it here.

**Comment by aacuevas** [comment]
It doesn't show on the current Windows binaries too, but it does on my working branch, so it was probably fixed in development at some point.

**Comment by sept-en** [comment]
As I remember I've changed the design of this top panel some months ago.
So now it looks like this. So, as @aacuevas mentioned it's fixed in the **development** branch.
![screenshot from 2016-08-27 01-30-33](https://cloud.githubusercontent.com/assets/7783792/18021076/078f2572-6bf6-11e6-93c1-9752d9e78dc2.png)

However, I think that we should somehow accent that this is exactly a button, not just a plain text. Maybe it's better change the text of it or replace text with some configuration icon? What do you think?


Best regards,
Kirill Abramov.

**Comment by mikewehr** [comment]
Can anyone point me to the bugfix that makes this button visible?
